version: 0.2

env:
  variables:
    env: "dev"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "**************** Stage - Install ****************"
      - npm install serverless -g
      - npm install
  build:
    commands:
      - echo "**************** Stage - Build ****************"
      - sls deploy -s dev

artifacts:
  files:
    - '**/*'
  base-directory: .serverless