service: serverless-template-api

provider:
  name: aws
  profile: scca
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}

functions:
  getMsg:
    handler: handler.hello
    events:
      - http: GET /
